function NextAppBaseTS {
    param (
        [Parameter(Mandatory = $true)]
        [string]$Project_Name
    )
    
    $Project_Name = $Project_Name.ToLower().Replace(" ", "-")
    pnpm create next-app@latest $Project_Name --ts --eslint --no-tailwind --src-dir --app --import-alias "@/*"
    Set-Location $Project_Name
    # Package Installer
    NextPackageTS

    "src/components/elements", "src/components/fragments", "src/components/layouts", "src/libs", "src/libs/axios", "src/features", "src/features/product", "src/features/user", "src/types", "public/assets/images", "public/assets/videos", "public/assets/audios" | ForEach-Object { New-Item -Path $_ -ItemType Directory -Force }

    $providersContent = @"
"use client"
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

type ProvidersProps = {
    children: React.ReactNode
}

export default function Providers({ children }: ProvidersProps) {
    return (
        <QueryClientProvider client={queryClient}>
            {children}
        </QueryClientProvider>
    )
}
"@
    Set-Content -Path src/app/Providers.tsx -Value $providersContent

    $apptsxLayout = @"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
"@
    Set-Content -Path src/app/layout.tsx -Value $appTsxLayout

    $appTsxContent = @"
export default function App() {
    return (
        <div className="container">
            <h1 className="title">Avnexcode</h1>
            <h1 className="title"><span>Prot Prot</span> Builder</h1>
            <h1 className="title">Next TS App Router Builder</h1>
        </div>
    );
}
"@        
    Set-Content -Path src/app/page.tsx -Value $appTsxContent

    $indexCssContent = @"
.container {
    background-color: #3b82f6; /* bg-blue-500 */
    color: white; /* text-white */
    padding: 1rem; /* p-4 */
    width: 100%; /* w-full */
    height: 100vh; /* h-screen */
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    gap: 1.25rem; /* gap-5 */
}

.title {
    font-size: 1.875rem; /* text-3xl */
    font-weight: bold; /* font-bold */
    text-transform: uppercase; /* uppercase */
}

.title span {
    text-transform: uppercase; /* uppercase */
}
"@
    Set-Content -Path src/app/globals.css -Value $indexCssContent

    code .
    pnpm run dev
}