function NextAppChakraUITS {
    param (
        [Parameter(Mandatory = $true)]
        [string]$Project_Name
    )

    $Project_Name = $Project_Name.ToLower().Replace(" ", "-")
    pnpm create next-app@latest $Project_Name --ts --eslint --tailwind --src-dir --app --import-alias "@/*"
    Set-Location $Project_Name
    # Style  Installer
    pnpm add @chakra-ui/react @emotion/react @emotion/styled framer-motion
    # Package Installer
    NextPackageTS

    "src/components/elements", "src/components/fragments", "src/components/layouts", "src/libs", "src/libs/axios", "src/features", "src/features/product", "src/features/user", "src/types", "public/assets/images", "public/assets/videos", "public/assets/audios" | ForEach-Object { New-Item -Path $_ -ItemType Directory -Force }

    $providersContent = @"
"use client"
import { ChakraProvider } from '@chakra-ui/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

type ProvidersProps = {
    children: React.ReactNode
}

export default function Providers({ children }: ProvidersProps) {
    return (
        <QueryClientProvider client={queryClient}>
            <ChakraProvider>
                {children}
            </ChakraProvider>
        </QueryClientProvider>
    )
}
"@
    Set-Content -Path src/app/Providers.tsx -Value $providersContent

    $apptsxLayout = @"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
"@
    Set-Content -Path src/app/layout.tsx -Value $appTsxLayout

    $appTsxContent = @"
import { Flex, Heading, Text } from "@chakra-ui/react";

export default function App() {
    return (
        <Flex justify={"center"} align={"center"} direction={"column"} color={"white"} backgroundColor={"blue"} gap={"8px"} h={"100vh"} w={"100%"} p={"5px"}>
            <Heading>Avnexcode</Heading>
            <Text><span className="uppercase">Prot Prot</span> Builder</Text>
            <Text>Next TS App Router x Chakra UI Builder</Text>
        </Flex>
    );
}
"@        
    Set-Content -Path src/app/page.tsx -Value $appTsxContent

$indexCssContent = @"
"@
    Set-Content -Path src/app/globals.css -Value $indexCssContent

    code .
    pnpm run dev
}