function NextAppChakraUIJS {
    param (
        [Parameter(Mandatory = $true)]
        [string]$Project_Name
    )
    
    $Project_Name = $Project_Name.ToLower().Replace(" ", "-")
    pnpm create next-app@latest $Project_Name --js --eslint --tailwind --src-dir --app --import-alias "@/*"
    Set-Location $Project_Name
    # Style  Installer
    pnpm add @chakra-ui/react @emotion/react @emotion/styled framer-motion
    # Package Installer
    NextPackageJS

    "src/components/elements", "src/components/fragments", "src/components/layouts", "src/libs", "src/libs/axios", "src/features", "src/features/product", "src/features/user", "public/assets/images", "public/assets/videos", "public/assets/audios" | ForEach-Object { New-Item -Path $_ -ItemType Directory -Force }

    $providersContent = @"
"use client"
import { ChakraProvider } from '@chakra-ui/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

export default function Providers({ children }) {
    return (
        <QueryClientProvider client={queryClient}>
            <ChakraProvider>
                {children}
            </ChakraProvider>
        </QueryClientProvider>
    )
}
"@
    Set-Content -Path src/components/layouts/Providers.js -Value $providersContent

    $appJsxLayout = @"
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layouts/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
"@
    Set-Content -Path src/app/layout.js -Value $appJsxLayout

    $appJsxContent = @"
import { Flex, Heading, Text } from "@chakra-ui/react";

export default function App() {
    return (
        <Flex justify={"center"} align={"center"} direction={"column"} color={"white"} backgroundColor={"blue"} gap={"8px"} h={"100vh"} w={"100%"} p={"5px"}>
            <Heading>Avnexcode</Heading>
            <Text><span className="uppercase">Prot Prot</span> Builder</Text>
            <Text>Next TS App Router x Chakra UI Builder</Text>
        </Flex>
    );
}
"@    
    Set-Content -Path src/app/page.js -Value $appJsxContent

$indexCssContent = @"
"@
    Set-Content -Path src/app/globals.css -Value $indexCssContent

    code .
    pnpm run dev
}